"""Grant report export for funder reporting requirements."""

from datetime import date

import orjson

from labpubs.export.cv_entries import format_apa
from labpubs.models import Award, Work


def export_grant_report_markdown(
    works: list[Work],
    award: Award | None = None,
    funder_name: str | None = None,
    include_abstract: bool = False,
) -> str:
    """Generate a markdown grant report.

    Args:
        works: List of works to include.
        award: Optional Award for header details.
        funder_name: Funder name for header.
        include_abstract: Include abstracts in output.

    Returns:
        Markdown-formatted report string.
    """
    lines: list[str] = []

    # Header
    if award:
        funder_display = award.funder.name if award.funder else funder_name or "Unknown"
        title = f"# Grant Report: {funder_display} Award #{award.funder_award_id}"
        lines.append(title)
        lines.append("")
        lines.append(f"**Funder:** {funder_display}  ")
        lines.append(f"**Award ID:** {award.funder_award_id}  ")
        if award.display_name:
            lines.append(f"**Award Title:** {award.display_name}  ")
        if award.lead_investigator:
            pi_parts = []
            if award.lead_investigator.given_name:
                pi_parts.append(award.lead_investigator.given_name)
            if award.lead_investigator.family_name:
                pi_parts.append(award.lead_investigator.family_name)
            pi_name = " ".join(pi_parts)
            orcid = award.lead_investigator.orcid or ""
            if orcid:
                pi_name += f" (ORCID: {orcid})"
            lines.append(f"**PI:** {pi_name}  ")
        if award.start_year:
            lines.append(f"**Start Year:** {award.start_year}  ")
        lines.append(f"**Publications:** {len(works)}")
    elif funder_name:
        lines.append(f"# Grant Report: {funder_name}")
        lines.append("")
        lines.append(f"**Funder:** {funder_name}  ")
        lines.append(f"**Publications:** {len(works)}")
    else:
        lines.append("# Grant Report")
        lines.append("")
        lines.append(f"**Publications:** {len(works)}")

    lines.append("")
    lines.append("## Publications")
    lines.append("")

    for i, work in enumerate(works, 1):
        citation = format_apa(work)
        lines.append(f"{i}. {citation}")

        extras: list[str] = []
        if work.doi:
            extras.append(f"DOI: {work.doi}")
        if work.open_access_url:
            extras.append(f"Open Access: {work.open_access_url}")
        if extras:
            lines.append(f"   {' | '.join(extras)}")

        if include_abstract and work.abstract:
            lines.append(f"   Abstract: {work.abstract}")

        lines.append("")

    lines.append("---")
    lines.append(
        f"*Generated by labpubs on {date.today().isoformat()}. Data from OpenAlex.*"
    )

    return "\n".join(lines)


def export_grant_report_json(
    works: list[Work],
    award: Award | None = None,
    funder_name: str | None = None,
) -> str:
    """Generate a JSON grant report.

    Args:
        works: List of works to include.
        award: Optional Award for metadata.
        funder_name: Funder name for metadata.

    Returns:
        JSON-formatted report string.
    """
    report: dict[str, object] = {
        "funder": funder_name,
        "publication_count": len(works),
        "publications": [w.model_dump(mode="json") for w in works],
    }
    if award:
        report["award"] = award.model_dump(mode="json")
        if award.funder:
            report["funder"] = award.funder.name

    return orjson.dumps(report, option=orjson.OPT_INDENT_2).decode()


def export_grant_report_csv(works: list[Work]) -> str:
    """Generate a CSV grant report.

    Args:
        works: List of works to include.

    Returns:
        CSV-formatted report string.
    """
    lines = ["title,year,venue,doi,authors"]
    for work in works:
        authors = "; ".join(a.name for a in work.authors)
        title = work.title.replace('"', '""')
        venue = (work.venue or "").replace('"', '""')
        doi = work.doi or ""
        year = str(work.year) if work.year else ""
        lines.append(f'"{title}",{year},"{venue}",{doi},"{authors}"')
    return "\n".join(lines)


def export_grant_report(
    works: list[Work],
    award: Award | None = None,
    funder_name: str | None = None,
    report_format: str = "markdown",
    include_abstract: bool = False,
) -> str:
    """Generate a grant report in the specified format.

    Args:
        works: List of works to include.
        award: Optional Award for metadata.
        funder_name: Funder name.
        report_format: 'markdown', 'json', or 'csv'.
        include_abstract: Include abstracts (markdown only).

    Returns:
        Formatted report string.

    Raises:
        ValueError: If format is not supported.
    """
    if report_format == "markdown":
        return export_grant_report_markdown(works, award, funder_name, include_abstract)
    if report_format == "json":
        return export_grant_report_json(works, award, funder_name)
    if report_format == "csv":
        return export_grant_report_csv(works)
    raise ValueError(
        f"Unsupported format: {report_format}. Supported: markdown, json, csv"
    )
